version: '3'
services:
  booking:
    build:
      context: .
      dockerfile: Dockerfile
    env_file:
      - .env
    command: npm run dev
    volumes:
      - .:/app/
      - /app/node_modules
    ports:
      - "3000:3000"
